config/routes.rb
KoSombo::Application.routes.draw do
  get "player/index"
  get "player/help"

  devise_for :users

  get "game/play"

  get "game/global"

  get "game/moderator"

  root :to => 'player#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def play
  end

  def global
  end

  def moderator
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def help
  end
end

app/controllers/websocket_controller.rb
require 'websocket_helper'
require 'net/http'

class WebsocketController < WebsocketRails::BaseController

  include WebsocketHelper

  def initialize_session
    unless controller_store[:id_num]
      controller_store[:id_num] = 0
      Thread.abort_on_exception = true
      Thread.new do
        puts "starting listener"
        # watch_pipe('redis')
        subscribe_to_redis
      end
    end
  end

  def connected
    puts "connection made!"
    # send_message :test, "hello!"
  end

  def send_event(send_channel, msg)
    if send_channel
      WebsocketRails[:"#{send_channel}"].trigger(:event, msg)
    else
      puts "no channel specified, skipping #{msg}"
      # WebsocketRails[:"#{controller_store[:current_event_id]}"].trigger(:event, msg)
    end

    # send_message :event, msg
  end

  def receive_event
    puts "received #{message}"
    controller_store[:current_event_id] = message[0]
    jss = ActiveSupport::JSON.decode(message[2])
    jss["clientID"] = message[0]
    jss["roomID"] = message[1]
    jss["deviseName"] = "#{current_user.email}"
    # write_pipe(ActiveSupport::JSON.encode(jss))
    if(jss["event"] == "changeSettings")
      send_event(jss["roomName"],ActiveSupport::JSON.encode(jss))
    end
    # puts "current #{current_user.email}"
    # else
    #if @mode == "redis"
      write_queue(ActiveSupport::JSON.encode(jss))
    #else
     # write_pipe(ActiveSupport::JSON.encode(jss))
    # end
    # end
    # puts "wrote"
  end

  def get_new_id
    trigger_success "#{controller_store[:id_num]}"
    controller_store[:id_num] += 1
  end

  def watch_pipe(mode)
    loop do
      # if mode == "redis"
      # puts "check queue"
      str = read_queue(true)
      # puts "read queue"
      puts "got #{str}"
      # else
      #   str = read_pipe
      # end
      obj = ActiveSupport::JSON.decode(str);

      if(obj["event"] == "changeSettings")
        send_channel = obj["roomName"]
      else
        send_channel = obj["clientID"]    #redundant?
      end

      puts "Sending #{str} to #{send_channel}"

      send_event(send_channel,str)
    end
  end

  def check_model
    if ENV["RAILS_ENV"] == "development"
      url = URI.parse('http://localhost:4567/start')
    else
      url = URI.parse('http://mysterious-cliffs-4762.herokuapp.com/start')
    end
    req = Net::HTTP::Get.new(url.path)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    trigger_success
  end

  def subscribe_to_redis
    if ENV["RAILS_ENV"] == "development"
      redis = REDISLOCALR
    else
      redis = REDISREAD
    end
    puts "subscribing"
    redis.subscribe(:toRuby) do |on|
      on.message do |channel, msg|
        data = JSON.parse(msg)
        puts "sending #{msg}"
        send_event(data["clientID"], msg)
        # puts "##{channel} - [#{data['user']}]: #{data['msg']}"
    end
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/watcher.rb
# puts ("#{sender} listieng on #{REDISREAD}")
# loop do
#   # if mode == "redis"
#   puts "poll"
#   if (str = REDISREAD.rpop("fromJava")[1]) # yay spin waiting
#     # else
#     #   str = read_pipe
#     # end
#     obj = ActiveSupport::JSON.decode(str);

#     if(obj["event"] == "changeSettings")
#       send_channel = obj["roomName"]
#     else
#       send_channel = obj["clientID"]    #redundant?
#     end

#     puts "Sending #{str} to #{send_channel}"

#     send_event(send_channel,str)
#   end
# end

app/helpers/websocket_helper.rb
module WebsocketHelper
  # def open_pipes(mode)
  #   if mode == "pipes"
  #     puts 'rails opening pipes'
  #     puts write = open("#{Rails.root}/pipes/javapipe",'r+')
  #     puts read = open("#{Rails.root}/pipes/rubypipe",'w+')
  #   else
  #     puts 'rails connecting to redis'
  #     uri = URI.parse("redis://redistogo:1f736fa2a27319dc45b7ebb470e04bbe@dory.redistogo.com:10177/")
  #     write = Redis.new(:host => uri.host, :port => uri.port, :password => uri.password)
  #     read = Redis.new(:host => uri.host, :port => uri.port, :password => uri.password)
  #   end
  #   puts "array #{[write,read]}"
  #   [write,read]
  #   # #puts "#{File.exist?('~/javapipe')}"
  #   # Dir.chdir(File.dirname(__FILE__))
  # end

  def write_pipe(pipe, msg)
    # puts "writing #{msg} to "

    pipe.puts(msg)
    pipe.flush
  end

  # def read_pipe
  #   red.gets
  # end

  def write_queue(msg)
    # REDISREAD.lpush("toJava", msg)
    if ENV["RAILS_ENV"] == "development"
      redis = REDISLOCALW
    else
      redis = REDISWRITE
    end
    redis.lpush("toJava", msg)
  end

  def read_queue(blocking)
    # puts "waiting to read"
    if ENV["RAILS_ENV"] == "development"
      redis = REDISLOCALR
    else
      redis = REDISREAD
    end

    if blocking==false

      # REDISWRITE.rpop("fromJava")
      redis.rpop("fromJava")
    else

      redis.brpop("fromJava")[1]
      # REDISWRITE.brpop("fromJava")[1]
    end
    # puts "read"
  end

end

app/views/game/global.html.erb
<!-- <link rel="stylesheet" href="http://extjs.cachefly.net/ext-4.1.1-gpl/resources/css/ext-all-access.css"> -->

<%= javascript_include_tag("globalView") %>

app/views/game/moderator.html.erb
  <link rel="stylesheet" href="http://extjs.cachefly.net/ext-4.1.1-gpl/resources/css/ext-all-access.css">
<%= javascript_include_tag("moderator") %>

app/views/game/play.html.erb
<link rel="stylesheet" href="http://extjs.cachefly.net/ext-4.1.1-gpl/resources/css/ext-all-access.css">
<%= javascript_include_tag("playerClient") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KoSombo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" href="http://extjs.cachefly.net/ext-4.1.1-gpl/resources/css/ext-all-access.css">
  <%# stylesheet_link_tag "ext-all-access" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/player/help.html.erb
<p><%= image_tag("help0.png") %></p>
<p><%= image_tag("help1.png") %></p>
<p><%= image_tag("help2.png") %></p>

app/views/player/index.html.erb
<!-- <h1>Player#index</h1>
<p>Find me in app/views/player/index.html.erb</p>
 -->
<link rel="stylesheet" href="http://extjs.cachefly.net/ext-4.1.1-gpl/resources/css/ext-all-access.css">

<p> <%= "Hello #{current_user.email}"  %> </p>

<p> <%= link_to "Play", game_play_path %> </p>
<p> <%= link_to "Moderate", game_moderator_path %> </p>
<p> <%= link_to "Watch", game_global_path %> </p>

<p> <br> <br> <%= link_to "Help", player_help_path %> </p>